//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace signup
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AugDBEntities : DbContext
    {
        public AugDBEntities()
            : base("name=AugDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SignupPage> SignupPages { get; set; }
    
        public virtual int sp_stinsert(string sna, string suna, string spwd, string scpwd)
        {
            var snaParameter = sna != null ?
                new ObjectParameter("sna", sna) :
                new ObjectParameter("sna", typeof(string));
    
            var sunaParameter = suna != null ?
                new ObjectParameter("suna", suna) :
                new ObjectParameter("suna", typeof(string));
    
            var spwdParameter = spwd != null ?
                new ObjectParameter("spwd", spwd) :
                new ObjectParameter("spwd", typeof(string));
    
            var scpwdParameter = scpwd != null ?
                new ObjectParameter("scpwd", scpwd) :
                new ObjectParameter("scpwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_stinsert", snaParameter, sunaParameter, spwdParameter, scpwdParameter);
        }
    }
}
